pipeline:
  name: docker
  identifier: docker
  projectIdentifier: firstproject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnect
        repoName: Docker-Zero-to-Hero
        build: <+input>
  stages:
    - stage:
        name: docker-push
        identifier: dockerpush
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker_connect
                    repo: sangameshhub/sample-dockerfile
                    tags:
                      - docker-image
